title: Virtual Velodrome Rider Application
author: Csaba Toth
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Virtual Velodrome Rider Application

twitter_username: tocsa2
github_username:  MrCsabaToth

google_analytics: UA-86563829-5

exclude:
  - "LICENSE"
  - "README.md"
  - ".gitignore"
plugins:
  - jekyll-redirect-from

sass:
    style: compressed
theme: jekyll-theme-minimal
