title: Track My Indoor Workout Application
author: Csaba Toth
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Track My Indoor Workout Application

twitter_username: tocsa2
github_username:  MrCsabaToth

google_analytics: UA-86563829-6
application_name: Track My Indoor Workout
app_source_repo: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/
app_issues: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/issues/
website_source_repo: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout.github.io/
website_issues: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout.github.io/issues/
app_store_url: https://play.google.com/store/apps/details?id=dev.csaba.track_my_indoor_exercise
kayakpro_url: https://www.kayakpro.com/kayakcanoe/kayak-genesis-port-smart-console/
swimfast_url: https://www.kayakpro.com/swimfast/
speedstroke_url: https://www.kayakpro.com/speedstrokepro/genesis-port-smart-console/
quick_start_video_url: https://www.youtube.com/watch?v=ntdPXvt-Uxw
strava_url: https://www.strava.com/
mapmyfitness_url: https://www.mapmyfitness.com/
mapmyrun_url: https://www.mapmyrun.com/
suunto_url: https://www.suunto.com/
sports_tracker_url: https://sports-tracker.com/
training_peaks_url: https://app.trainingpeaks.com/

exclude:
  - "LICENSE"
  - "README.md"
  - ".gitignore"
plugins:
  - jekyll-redirect-from

sass:
    style: compressed
theme: jekyll-theme-minimal
