title: Track My Indoor Workout Application
author: Csaba Toth
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Track My Indoor Workout Application

twitter_username: tocsa2
github_username:  MrCsabaToth

google_analytics: UA-86563829-5
app_store_url: https://play.google.com/store/apps/details?id=dev.csaba.track_my_indoor_exercise

exclude:
  - "LICENSE"
  - "README.md"
  - ".gitignore"
plugins:
  - jekyll-redirect-from

sass:
    style: compressed
theme: jekyll-theme-minimal
