title: Track My Indoor Workout Application
author: Csaba Toth
company: Csaba Consulting
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Track My Indoor Workout Application

twitter_username: tocsa2
github_username:  MrCsabaToth

google_analytics: UA-86563829-6
application_name: Track My Indoor Workout
app_source_repo: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/
app_issues: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/issues/
website_source_repo: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout.github.io/
website_issues: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout.github.io/issues/
play_store_url: https://play.google.com/store/apps/details?id=dev.csaba.track_my_indoor_exercise
galaxy_store_url: https://galaxy.store/tmiw
huawei_appgallery_url: https://appgallery.cloud.huawei.com/ag/n/app/C106464631?channelId=app_website&referrer=https%3A%2F%2Ftracmyindoorworkout.github.io%2F&id=c50a17eaffa34e1f9699157b5d2a190b&s=812550EDCEE476DDC6A041F2DADEF2245CD128C41F98CD61D9D5EEEBBBAD0FFF&detailType=0&v=&callType=AGDLINK&installType=0000
kayakpro_site_url: https://kayakpro.com/
kayakpro_url: https://www.kayakpro.com/kayakcanoe/kayak-genesis-port-smart-console/
swimfast_url: https://www.kayakpro.com/swimfast/
speedstroke_url: https://www.kayakpro.com/speedstrokepro/genesis-port-smart-console/
quick_start_video_url: https://www.youtube.com/watch?v=ntdPXvt-Uxw
strava_url: https://www.strava.com/
mapmyfitness_url: https://www.mapmyfitness.com/
mapmyrun_url: https://www.mapmyrun.com/
suunto_url: https://www.suunto.com/
sports_tracker_url: https://sports-tracker.com/
training_peaks_url: https://app.trainingpeaks.com/
mr_captain_url: https://mr-captain.com/
mr_captain_rower_url: https://mr-captain.com/collections/rowing-machine
technogym_skillrow_url: https://www.technogym.com/us/skillrow.html
by_me_a_coffee_url: https://www.buymeacoffee.com/tocsa
ko_fi_me_url: https://Ko-fi.com/tocsa
venmo_url: https://venmo.com/code?user_id=2114670181744640341&created=1670822626
cash_app_url: https://cash.app/$CsabaToth?qr=1
zelle_url: https://enroll.zellepay.com/qr-codes?data=eyJuYW1lIjoiQ1NBQkEiLCJhY3Rpb24iOiJwYXltZW50IiwidG9rZW4iOiJjc2FiYS50b3RoLnVzQG91dGxvb2suY29tIn0=
stages_sc3_url: https://stagescycling.com/en_us/stages-indoor-cycle-sc3-2
stages_sic2_url: https://manuals.stagesindoorcycling.com/en/indoor-console/sic2/
stages_sb20_url: https://stagescycling.com/en_us/stages-sb20-smart-bike-indoor-cycle
wahoo_kickr_url: https://www.wahoofitness.com/devices/indoor-cycling/bike-trainers/kickr-buy-v5
wahoo_rpm_speed_sensor_url: https://www.wahoofitness.com/devices/bike-sensors/bluetooth-speed-sensor
wahoo_rpm_cadence_sensor_url: https://www.wahoofitness.com/devices/bike-sensors/wahoo-rpm-cadence-sensor
schwinn_ic4_url: https://www.schwinnfitness.com/ic4/100873.html
schwinn_ic8_url: https://global.schwinnfitness.com/en/ic8/100893.html
bowflex_c6_url: https://www.bowflex.com/bikes/c6/100894.html
schwinn_510u_url: https://global.schwinnfitness.com/en/510u/i100931.html
schwinn_170_url: https://www.schwinnfitness.com/170/100513.html
schwinn_270_url: https://www.schwinnfitness.com/270/100515.html
schwinn_570u_url: https://global.schwinnfitness.com/en/570u/100529.html
yesoul_s3_url: https://www.yesoulfitness.com/shop/yesoul-s3-indoor-cycling-bike-black/
lifepro_flexstride_pro_url: https://lifeprofitness.com/products/flexstride-pro-calf-leg-foot-pedal-exerciser

exclude:
  - "LICENSE"
  - "README.md"
  - ".gitignore"
plugins:
  - jekyll-redirect-from

sass:
    style: compressed
theme: jekyll-theme-minimal
